version: 2.1

orbs:

  python: circleci/python@2.0.3

jobs:
  flake8 and manage_py_test:
    executor: python/3.10.4
    environment:
      DJANGO_SECRET_KEY: django-insecure
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run: python manage.py migrate
      - run: python manage.py test

workflows:
  run tests:
    jobs:
      - flake8 and manage_py_test